# Generated by Django 4.2.1 on 2023-06-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_product_category_remove_product_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.URLField()),
                ('name', models.TextField()),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField(default=0)),
            ],
        ),
    ]
