# Generated by Django 4.2.1 on 2023-06-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_cart_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_product',
            name='p_key',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='p_key',
            field=models.IntegerField(default=0),
        ),
    ]
