# Generated by Django 4.2.1 on 2023-06-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_cart_product_p_key_product_p_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_product',
            name='qty',
            field=models.IntegerField(default=0),
        ),
    ]
