# Generated by Django 4.2.1 on 2023-06-10 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_cart_product_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_product',
            name='p_key',
        ),
        migrations.RemoveField(
            model_name='product',
            name='p_key',
        ),
    ]
