# Generated by Django 4.2.1 on 2023-06-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_cart_product_p_key_remove_product_p_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='incart',
        ),
        migrations.AddField(
            model_name='cart_product',
            name='p_key',
            field=models.CharField(default='a', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='p_key',
            field=models.CharField(default='a', max_length=50),
        ),
    ]
