# Generated by Django 4.2.1 on 2023-06-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_product_incart_cart_product_p_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_product',
            name='qty',
            field=models.IntegerField(default=1),
        ),
    ]
