# Generated by Django 4.2.1 on 2023-06-14 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_cart_product_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_product',
            name='customer',
            field=models.ManyToManyField(to='api.product'),
        ),
    ]
