# Generated by Django 4.2.1 on 2023-06-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_cart_product_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_product',
            name='customer',
        ),
        migrations.AddField(
            model_name='product',
            name='customer',
            field=models.ManyToManyField(to='api.cart_product'),
        ),
    ]
