# Generated by Django 4.2.1 on 2023-06-14 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_cart_product_customer_product_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='customer',
        ),
    ]
